# Generated by Django 5.0.1 on 2024-02-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_habit_created_remove_habit_updated_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
